lib/python/requirements.txt
lib/python/setup.py

Update to thrift 0.10.0 instead of our fork of thrift which is in an in between state of 0.9.3 and 0.10.0. Cross language tests are passing, which execute a lot of functionality.

Update to thrift==0.10.0

---

lib/dart/lib/src/frugal.dart
lib/dart/lib/src/frugal/transport/base_f_transport_monitor.dart
lib/dart/lib/src/frugal/transport/f_adapter_transport.dart
lib/dart/lib/src/frugal/transport/f_async_transport.dart
lib/dart/lib/src/frugal/transport/f_transport.dart
lib/dart/lib/src/frugal/transport/f_transport_monitor.dart
lib/dart/lib/src/frugal/transport/monitor_runner.dart
lib/dart/lib/src/frugal/transport/t_framed_transport.dart
lib/dart/pubspec.yaml
lib/dart/test/transport/f_transport_test.dart

I'm not sure how much of this is necessary as, in the browser, transports are usually very long lived. For the case of the nats transport (not in this repo, but extends classes in here) I believe one is instantiated at load time and used for the duration of the session.
Either way, I think the completer cleanup on messages needed to happen.
@Workiva/messaging-pp 
@Workiva/performance-reviewers I was told one of you could look over this to make sure everything looks fine

Memory fixes for GRC

---

compiler/generator/dartlang/generator.go
examples/dart/gen-dart/v1_music/lib/src/f_store_service.dart
test/expected/dart/actual_base/f_base_foo_service.dart
test/expected/dart/include_vendor/f_my_service_service.dart
test/expected/dart/variety/f_foo_service.dart

This naming of our logger was causing a conflict when an IDL as `log()` as a service method. This added a frugal prefix, which I intended to be viewed as a "reserved" prefix, implying users should not use this prefix for the names in their IDL
@Workiva/messaging-pp @markerickson-wf

change log name in dart generated code

---

.travis.yml

@Workiva/messaging-pp travis-ci updated their default builder. Pinning to the previous version that we know passes until have time to figure it out, as to not hold up releases and other PRs.

Use older version of travis worker so build passes

---

compiler/generator/html/generator.go
lib/python/requirements.txt
lib/python/setup.py
test/expected/dart/variety/f_awesome_exception.dart
test/expected/dart/variety/f_event.dart
test/expected/dart/variety/f_event_wrapper.dart
test/expected/dart/variety/f_test_base.dart
test/expected/dart/variety/f_test_lowercase.dart
test/expected/dart/variety/f_testing_defaults.dart
test/expected/dart/variety/f_testing_unions.dart
test/expected/dart/variety/f_variety_constants.dart
test/expected/dart/variety/variety.dart
test/expected/go/variety/f_types.txt
test/expected/html/index.html
test/expected/html/standalone/index.html
test/expected/html/standalone/variety.html
test/expected/html/variety.html
test/expected/python.asyncio/variety/constants.py
test/expected/python.asyncio/variety/ttypes.py
test/expected/python.tornado/variety/constants.py
test/expected/python.tornado/variety/ttypes.py
test/expected/python/variety/constants.py
test/expected/python/variety/ttypes.py
test/idl/intermediate_include.frugal
test/idl/variety.frugal

If a dependency was included multiple times via a transitive dependency, like `b` depends on `a` and `c` depends on both `b` and `a`, then `a` shouldn't be shown multiple times in the index generated by the html generator.
@Workiva/messaging-pp @markcampanelli-wf

don't show dependencies multiple times in the html index

---

lib/python/frugal/serialize.py
test/integration/python/common/test_serialize.py

Add frugal serialize functions which cope with unicode string values for structure properties. They are not handled by Thrift serialize functions with frugal generated code.

Add serialize functions with tests

---

lib/java/src/main/java/com/workiva/frugal/processor/FBaseProcessor.java

Unhandled exceptions are logged like:
```
[pool-3-thread-1] User handler code threw unhandled exception on request with correlation ided5c238e5701404693ab883fc1e7ba4d
```
Notice there is no space between "id" and the actual correlation id, which makes it harder to search for correlation ids.

java: Add missing space to unhandled exception log

---

lib/java/src/main/java/com/workiva/frugal/transport/FHttpTransport.java
lib/java/src/test/java/com/workiva/frugal/transport/FHttpTransportTest.java

Add `getRequestHeaders(FContext)` to `FHttpTransportHeaders`.  Implement it as a default method that calls `getRequestHeaders()` so that behavior of existing implementations is unchanged.
Fixes #920

java: Add FHttpTransportHeaders.getRequestHeaders(FContext)

---

lib/python/requirements_dev_asyncio.txt
lib/python/setup.py

https://github.com/Workiva/frugal/blob/master/lib/python/requirements_dev_asyncio.txt
frugal[asyncio] points to asyncio-nats-client==0.3.1
https://github.com/Workiva/messaging-sdk/blob/master/lib/python/messaging_sdk/aio/nats.py#L94
messaging_sdk pass tls parameters, but tls is introduced in asyncio-nats-client 0.6.0 https://github.com/nats-io/asyncio-nats/blame/master/nats/aio/client.py#L151

bump asyncio-nat-client version to 0.6.0

---

lib/python/frugal/aio/transport/http_transport.py
lib/python/frugal/tests/aio/transport/test_http_transport.py
lib/python/frugal/tests/tornado/transport/test_http_transport.py
lib/python/frugal/tornado/transport/http_transport.py

added `get_request_header` function to tornado and asyncio's `FHttpTransport`.  By default it will not add any additional headers onto the request so existing implementation is not effected, but can be overridden by a consumer to append additional headers.
Addresses #920 and based off changes in #922

Python: Add param to allow for additional request headers to FHTTPTransport #927

---

lib/go/http_transport.go
lib/go/http_transport_test.go

go equivalent of recent python changes - https://github.com/Workiva/frugal/pull/928
Allows consumer to pass in a function that accepts an FContext.  This function should return additional request headers to be appended on a per-request basis.
Also fixes issue where default request headers would not have been overwritten.  `http.Header.Add` will append to existing headers, not overwrite them.

go: add WithRequestHeadersFromFContext to FHttpTransportBuilder

---

lib/dart/lib/src/frugal/transport/f_http_transport.dart
lib/dart/test/transport/f_http_transport_test.dart

dart equivalent of recent python changes - https://github.com/Workiva/frugal/pull/928
Allows consumer to pass in a function that accepts an FContext using the `getRequestHeaders` parameter.  This function should return additional request headers to be appended on a per-request basis.

dart: add getRequestHeaders param to FHttpTransport

---

.gitignore
lib/python/Makefile
lib/python/frugal/tests/aio/server/test_http_handler.py
lib/python/requirements.txt
lib/python/requirements_dev_asyncio.txt
lib/python/setup.py
scripts/skynet/cross/setup_python.sh
test/integration/python/asyncio/client.py
test/integration/python/common/utils.py

This isolates the issue fix from https://github.com/Workiva/frugal/pull/930. I'll wait on adding the changes to the skynet cross tests until the switch from Godeps is complete. One of the cross test changes is to make it output a csv table with all the variables and outcome of each client/server combination test. It makes it so you can quickly find the factors associated with failures and would have made finding this fix a lot faster.
Move multidict to its proper place in asyncio extras
Fix issue where integration test couldn't handle some exceptions
Work around bug in aiohttp
Pull requests should be made against the 'develop' branch, not master.

Move multidict requirement to asyncio extras

---

lib/dart/lib/frugal.dart

GetHeadersWithContext was not exposed in #934 

dart: exposes GetHeadersWithContext

---

lib/java/src/main/java/com/workiva/frugal/server/FNatsServer.java
lib/java/src/main/java/com/workiva/frugal/transport/FAdapterTransport.java
lib/java/src/test/java/com/workiva/frugal/server/FNatsServerTest.java
lib/java/src/test/java/com/workiva/frugal/transport/FAdapterTransportTest.java

If an exception is thrown from a task passed to `ExecutorService.submit`, the exception is captured in the returned `Future`.  If the `Future` is ignored, the exception message+stack is lost, which is problematic if `Error` is thrown from a request processor.  Use `ExecutorService.execute` in those cases, which allows the default exception handler to print the exception message+stack.

Java: Use ExecutorService.execute instead of submit if Future is unused

---

compiler/generator/dartlang/generator.go
test/expected/dart/variety/f_foo_service.dart

Currently, the message from the `(deprecated="...")` annotation is not propagated to the abstract base class ("interface"), so it is not easily visible to clients.  Add `/// Deprecated: ...`.
Additionally, use the same pattern in the client class rather than `@Deprecated("...")` since that syntax sets an "expires" member that is used to describe when the member will be removed rather than being used as a general string to describe the deprecation, which is how it is used elsewhere.

dart: Add deprecated comment to abstract classes

---

lib/python/requirements_dev_asyncio.txt
lib/python/setup.py

This was somehow breaking asyncio nats with tls. I spent the day trying to figure out how/why and didn't come up with anything, so I decided to just bump the version down.
The problem is somewhere in https://github.com/aio-libs/multidict/compare/v3.1.3...v3.2.0#diff but I wasn't able to nail it down further

change version of multidict

---

compiler/generator/java/generator.go
lib/java/src/main/java/com/workiva/frugal/processor/FBaseProcessor.java
lib/java/src/main/java/com/workiva/frugal/server/FNatsServer.java
lib/java/src/test/java/com/workiva/frugal/server/FNatsServerTest.java
test/expected/java/actual_base/FBaseFoo.java
test/expected/java/boxed_primitives/FFoo.java
test/expected/java/variety/FFoo.java
test/expected/java/variety_async/FFoo.java

(Updated #953 to fix build by keeping the same `TApplicationException` message.)
Three commits are intended to be reviewed independently, but all three improve Java exception handling:
1. Improve logging of undeclared `TException`.  See commit message for more details.
2. Document lack of `writeApplicationException` for `TException` in `FBaseProcessor`.  Noticed while trying to understand the exception handling of item 1 above.
3. Don't log RuntimeException twice for NATS.  As of commit 21758e33, RuntimeException are logged twice: once in `FBaseProcessor` and again by the Java uncaught exception handler.

Java: Improve exception handling

---

lib/python/requirements_dev_asyncio.txt
lib/python/setup.py

@Workiva/messaging-pp @Workiva/infre-product 
yarl released 1.0 which had some breaking changes, and aiohttp was pinned to yarl version >0.11, causing problems in our build

upgrade aiohttp to fix yarl issue

---

compiler/generator/golang/generator.go
examples/dart/web/index.html
examples/go/gen-go/v1/music/f_store_service.go
test/expected/go/variety/f_foo_service.txt
test/expected/go/variety_async/f_foo_service.txt
test/expected/go/vendor/f_myservice_service.txt

If a client side middleware returns nil for the rpc return value (such as in the case of an error where the middleware doesn't necessarily know what type to return) we were trying to type assert nil to the proper type, causing a panic.
@Workiva/messaging-pp @Workiva/infre-product @tannermiller-wf

handle returning nil in a go middleware properly

---

compiler/generator/python/asyncio.go
test/expected/python.asyncio/actual_base/f_BaseFoo.py
test/expected/python.asyncio/service_extension_same_file/f_BasePinger.py
test/expected/python.asyncio/service_extension_same_file/f_Pinger.py
test/expected/python.asyncio/variety/f_Foo.py

```python
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from graph_api.asyncio.api_data_types.ttypes import GraphServiceError
>>> e = GraphServiceError(isTransient=True)
>>> print(e.args)
()
>>> print(str(e))
GraphServiceError(isTransient=True, code=None, message=None, location=None)
>>>
```
@brianshannan-wf

Better asyncio exception handling

---

compiler/generator/dartlang/generator.go
examples/dart/gen-dart/v1_music/lib/src/f_album.dart
examples/dart/gen-dart/v1_music/lib/src/f_purchasing_error.dart
examples/dart/gen-dart/v1_music/lib/src/f_store_service.dart
examples/dart/gen-dart/v1_music/lib/src/f_track.dart
test/expected/dart/actual_base/f_api_exception.dart
test/expected/dart/actual_base/f_base_foo_service.dart
test/expected/dart/actual_base/f_nested_thing.dart
test/expected/dart/actual_base/f_thing.dart
test/expected/dart/include_vendor/f_my_service_service.dart
test/expected/dart/variety/f_awesome_exception.dart
test/expected/dart/variety/f_event.dart
test/expected/dart/variety/f_event_wrapper.dart
test/expected/dart/variety/f_foo_service.dart
test/expected/dart/variety/f_test_base.dart
test/expected/dart/variety/f_test_lowercase.dart
test/expected/dart/variety/f_testing_defaults.dart
test/expected/dart/variety/f_testing_unions.dart
test/expected/dart/vendor_namespace/f_item.dart

ticket: https://jira.atl.workiva.net/browse/INFENG-4889
Adds an `==` method and `clone()` method to dart structs, which take optional arguments to replace the current fields with.
@Workiva/messaging-pp @Workiva/infre-product @tayloranderson-wf

dart: add an equality operator and clone method for structs

---

compiler/generator/python/generator.go
lib/python/frugal/tests/util/test_make_hashable.py
lib/python/frugal/util/__init__.py
test/expected/python.asyncio/actual_base/ttypes.py
test/expected/python.asyncio/variety/f_Foo.py
test/expected/python.asyncio/variety/ttypes.py
test/expected/python.tornado/actual_base/ttypes.py
test/expected/python.tornado/variety/f_Foo.py
test/expected/python.tornado/variety/ttypes.py
test/expected/python/actual_base/f_BaseFoo.py
test/expected/python/actual_base/ttypes.py
test/expected/python/package_prefix/f_Foo.py
test/expected/python/package_prefix/ttypes.py
test/expected/python/variety/f_Foo.py
test/expected/python/variety/ttypes.py

Lists, sets, and maps aren't hashable in python. This converts said structures to a hashable form so the `__hash__` function should work in the generated code.
@Workiva/infre-product @Workiva/messaging-pp @sagesmith-wf @theisensanders-wf

Python make generated struct hashable

---

lib/java/src/main/java/com/workiva/frugal/FContext.java
lib/java/src/test/java/com/workiva/frugal/FContextTest.java

It is useful to be able to clone an FContext in order to clone correlation id, tracing, etc. headers but to remove others.

java: Add FContext methods to remove headers

---

compiler/generator/java/generator.go
test/expected/java/actual_base/nested_thing.java
test/expected/java/actual_base/thing.java
test/expected/java/boxed_primitives/FFoo.java
test/expected/java/boxed_primitives/TestingDefaults.java
test/expected/java/variety/AwesomeException.java
test/expected/java/variety/Event.java
test/expected/java/variety/EventWrapper.java
test/expected/java/variety/FFoo.java
test/expected/java/variety/TestBase.java
test/expected/java/variety/TestLowercase.java
test/expected/java/variety/TestingDefaults.java
test/expected/java/variety_async/FFoo.java

It is confusing to output a `// required` comment for fields that have default requiredness.

java: Avoid comment for default requiredness

---

lib/java/pom.xml
lib/java/src/main/java/com/workiva/frugal/server/FServlet.java
lib/java/src/test/java/com/workiva/frugal/server/FServletTest.java

The existing `FNettyHttpHandler` works well, but the asynchronous nature of the Netty programming model is more difficult to use than the servlet programming model for non-Frugal use cases.  Add a servlet so that Frugal can easily be included in the same server as other servlets.

java: Add FServlet

---

compiler/generator/dartlang/generator.go
compiler/generator/golang/generator.go
compiler/generator/html/module_template.go
compiler/generator/java/generator.go
compiler/generator/python/generator.go
test/expected/dart/enum/f_testing_enums.dart
test/expected/dart/variety/f_health_condition.dart
test/expected/go/variety/f_types.txt
test/expected/html/base.html
test/expected/html/standalone/base.html
test/expected/html/standalone/variety.html
test/expected/html/variety.html
test/expected/java/variety/HealthCondition.java
test/expected/python.asyncio/variety/ttypes.py
test/expected/python.tornado/variety/ttypes.py
test/expected/python/variety/ttypes.py
test/idl/enum.frugal
test/idl/variety.frugal

Commits are intended to be reviewed independently:
* Clean up Dart "doc comment" mentioned in [previous PR review](https://github.com/Workiva/frugal/pull/985#discussion_r177766884)
* Support deprecated annotation for enum values using the same pattern as #985.  The one caveat is that Dart enum values do not support annotations (see comment in code), so we just generate a comment for those.

Support deprecated annotation for enum values

---

compiler/generator/generator.go
compiler/generator/python/generator.go
test/python_test.go

When given an absolute path for the output directory, the existing SetupGenerator
code for python either went into an infinite loop once it hit the filesystem root
when walking up the directory hierarchy or would silently error once it hit a
folder the running user did not have write permission. Additionally, the existing
algorithm would cause __init__.py to be created in folders unrelated to frugal code
generation simply because the folder existed along the relative path given for output
directory
Update the python generation code to
- Respect errors returned by the SetupGenerator method
- Only generate __init__.py files in the folders that exist between the root output
directory and the target output directory for the generator. This change also
addresses the potential infinite loop …

Python: Allow generation using absolute output directory path

---

lib/python/setup.py

The frugal python package pins its versions which causes warnings for consumers if the versions aren't exactly resolved. It would be nice to open up those ranges some so that this doesn't occur.
@Workiva/messaging-pp @Workiva/product2 @georgelesica-wf

INFENG-5834: Allow loose pinning of minor versions of requests and six

---

lib/java/src/main/java/com/workiva/frugal/transport/FHttpTransport.java

In #1005, I convinced myself the timeout exception messages had sufficient context, but while debugging an issue, I found that it would have been helpful if there were more context.

java: Include cause for HTTP timeout exception

---

lib/dart/pubspec.yaml

The current version range on the `uuid` dependency is not compatible with Dart 2.
The latest version of `uuid` is compatible with both Dart 1 and 2, and contains no breaking changes.
Update the allowed version range of `uuid`.

Update uuid version range for Dart 2

---

lib/python/frugal/tests/aio/utils.py
lib/python/requirements.txt
lib/python/requirements_dev_asyncio.txt
lib/python/setup.py

Latest version of asyncio-nats-client includes python3.7 support.
Additionally, generic python requirements should be pinned to a major version to pick up minor version changes and give consumers flexibility in which versions they choose to use. I removed the explicit multidict requirement because it seems that at some point this became unnecessary https://github.com/Workiva/frugal/pull/946
Lastly, I got the tests running on Python3.7 locally but didn't upgrade runner image because it's more work than it's worth.

Upgrade asyncio-nats-client; Loosen python requirements

---

examples/java/pom.xml
examples/java/src/main/java/examples/ActiveMQPublisher.java
examples/java/src/main/java/examples/ActiveMQSubscriber.java
lib/java/pom.xml
lib/java/src/main/java/com/workiva/frugal/transport/FJmsPublisherTransport.java
lib/java/src/main/java/com/workiva/frugal/transport/FJmsSubscriberTransport.java
lib/java/src/main/java/com/workiva/frugal/transport/FNatsSubscriberTransport.java
lib/java/src/test/java/com/workiva/frugal/transport/FJmsPublisherTransportTest.java
lib/java/src/test/java/com/workiva/frugal/transport/FJmsSubscriberTransportTest.java
scripts/skynet/cross/setup_java.sh
scripts/skynet/skynet_setup.sh
test/integration/crossrunner/load.go
test/integration/crossrunner/run.go
test/integration/crossrunner/test.go
test/integration/java/frugal-integration-test/pom.xml
test/integration/java/frugal-integration-test/src/main/java/com/workiva/TestPublisher.java
test/integration/java/frugal-integration-test/src/main/java/com/workiva/TestSubscriber.java
test/integration/java/frugal-integration-test/src/main/java/com/workiva/Utils.java
test/integration/tests.json

Implements a JMS transport for frugal that could be used to communicate with active mq. I think all the major functionality exists, but might make some small changes. Some points
- Not super happy about how I ended up using the JMS session and producer/consumer in almost the same way (creating a session then immediately creating a producer, and also closing at the same time). The other possibility I see is sharing a session across multiple publishers/subscribers, but I was a little concerned as the documentation said sessions are not threadsafe, and I didn't want to coordinate that between transports. But I might have misunderstood how that API is supposed to work.
- The frugal transport API doesn't expose a good way to specify a message group per publish (for ordering), and I'm not sure …

Java jms transport

---

lib/python/frugal/aio/processor.py
lib/python/frugal/processor.py
lib/python/frugal/tornado/processor.py

I want to be able to mute the "frugal: exception occurred while processing request with..." error log and raise it myself within my logging middleware so that it includes application metadata. 
I noticed there was a logger already setup in these files that wasn't always being used which will allow me to easily mute these.

Python: Use file logger for processor exceptions

---

Dockerfile
skynet.yaml

Remove dartium and content-shell from messaging-docker-images.
None
Tests pass
Pass

Update to messaging-docker-images 0.0.30

---

lib/dart/lib/src/frugal/transport/f_http_transport.dart
lib/dart/test/transport/f_http_transport_test.dart

Set a timeout on the w_transport request object instead of relying on timing out with the future, as the default timeout for the http request (in w_transport) is 30s and the frugal timeout could be longer than that.
None
Make sure modified unit tests are sensible. You can optionally pull down the example code and run the dart client against a slowed server to show that a `TError` with type `3` is thrown.
Unit tests pass. I modified to example code to show that a timeout was thrown. Upon considering this, I wonder if the x-lang tests wouldn't benefit from a timeout exception test.
https://jira.atl.workiva.net/browse/INFENG-6562

dart: Use timeoutThreshold to set http timeout

---

Dockerfile
skynet.yaml

We need to give aviary what he ... err ... she ... wants!
I went with a stateless pub/sub server/client dependency injection model to refactor the docker scratch image to support the nobody *nix user.
```bash
docker run -it drydock.workiva.net/workiva/frugal:1575160 --help
```
```
$ docker run -it drydock.workiva.net/workiva/frugal:1575160 --help
Unable to find image 'drydock.workiva.net/workiva/frugal:1575160' locally
1575160: Pulling from workiva/frugal
a217dc0ab271: Already exists
8532ff613d02: Already exists
Digest: sha256:5d311e1d546e92037062d29ee8369ccba4fdc86beaf3bd43cd065128ba75ec4c
Status: Downloaded newer image for drydock.workiva.net/workiva/frugal:1575160
NAME:
frugal - a tool for code generation
USAGE:
frugal [global options] [arguments...]
GLOBAL OPTIONS:
--help, -h     show …
```

INFENG-6986 update docker image and use nobody user in dockerfile

---

lib/java/src/main/java/com/workiva/frugal/server/FNatsServer.java

Bump the core thread pool size for the default executor service for a FNatsServer. This means the default executor service will always have the maximum number of threads, but this trade off seems worth it given how thread pool executors scale threads. The executor service doesn't scale up threads until there are `queueLength` items waiting to be processed, which is very undesirable. I don't think there are many cases where having less than the maximum number of threads is desired.
A lot of teams currently supply their own executor service, but this should help teams who use the default one.
@Workiva/product2 @brettkail-wk

bump nats core pool size

---

lib/java/src/main/java/com/workiva/frugal/server/FNatsServer.java
lib/java/src/test/java/com/workiva/frugal/server/FNatsServerTest.java

When stopping a FNatsServer, the stop method awaits the server's
configured executor service for up to a defined number of seconds.
This is to give the server time to finish processing current tasks.
This time use to be hard coded to 30 seconds. Different servers may
have different needs, however. Allowing callers to both configure
the stop timeout for the server or to specify a timeout while calling
stop will enable additional use cases where a timeout other than the
default is desired.
Existing behavior should not change.
Unit testing added.
Passed locally.

Allow setting the stop timeout for stopping a FNatsServer

---

lib/java/pom.xml
test/integration/java/frugal-integration-test/pom.xml

https://github.com/nats-io/java-nats/releases/tag/2.4.3 is released which contains our fixes for reconnects.

Update jnats to 2.4.3

---

lib/java/src/main/java/com/workiva/frugal/server/FNatsServer.java
lib/java/src/test/java/com/workiva/frugal/server/FNatsServerTest.java

Previously, if a stop signal came in, the executor service was shutdown
prior to unsubscribing to the nats messages for the server. This would
lead to nats messages still being delivered to the server despite that
the messages will never be executed / acted upon because the executor
service was shutdown.
This changes the stop / shutdown process to first wait for the
unsubscriptions to finish prior to shutting down the executor service.
Thus, no new messages should be received from the nats server while
this frugal server is shutting down.
While it may be intended that people only call `serve` once and `stop` once on a FServer instance, I tried to design this so that if someone had a bug where they were calling these methods multiple times that this change should still work (blocking and …

Wait for unsubscribes to finish before shutting down executor service.

---

lib/java/src/main/java/com/workiva/frugal/transport/FHttpTransport.java
lib/java/src/test/java/com/workiva/frugal/transport/FHttpTransportTest.java

For retry purposes, it would be helpful to have an explicit error code.
Apache HTTP client throws `NoHttpResponseException` when the server has closed the exception before sending any response, so `END_OF_FILE` felt most appropriate.

java: Explicitly handle NoHttpResponseException

---

compiler/generator/dartlang/generator.go
examples/dart/gen-dart/v1_music/lib/src/f_store_service.dart
test/expected/dart/actual_base/f_base_foo_service.dart
test/expected/dart/include_vendor/f_my_service_service.dart
test/expected/dart/variety/f_foo_service.dart

Frugal's dart generation generates accessor methods which return Future's containing some requested data. Here's a typical example:
```
Future<List<t_comments.UserData>> getUserDataForAccount(frugal.FContext ctx) {
return this._methods['getUserDataForAccount']([ctx]) as Future<List<t_comments.UserData>>;
}
```
Unfortunately, the cast can only infer the wrapping type (`Future`) and not the underlying type parameter. This causes the returned type to be inferred as `Future<dynamic>`, regardless of the actual type parameter, leading to runtime errors like this on Dart 2:
```
error: Type '_Future<dynamic>' should be '_Future<List<t_comments.UserData>>' to implement expected type 'Future<List<t_comments.UserData>>'.
```
To fix this, we add a `.then` and explicitly cast the type parameter in a …

CPLAT-5534: Cast inner types on returned futures

---

lib/java/pom.xml
test/integration/java/frugal-integration-test/pom.xml

jnats [released](https://github.com/nats-io/nats.java/releases) new patch versions with a few bug fixes.
Pulled jnats 2.4.6 into java-nats-load-app, deployed to squad2, confirmed everything works. Bounced nats a few times, confirmed all connections were able to reconnect. 

Consume jnats 2.4.6

---

Dockerfile
lib/go/context.go
skynet.yaml

While working on https://jira.atl.workiva.net/browse/INFENG-8048 I noticed this [unit test](https://github.com/Workiva/messaging-sdk/blob/master/lib/go/sdk/iam_test.go#L511) is failing because `ephemeralProperties` is initialized in [Clone](https://github.com/Workiva/frugal/blob/master/lib/go/context.go#L126-L130) but not in [NewFConext](https://github.com/Workiva/frugal/blob/master/lib/go/context.go#L158-L165).   
Workiva-build is failing for a different reason now, should be fixed after https://github.com/Workiva/messaging-docker-images/pull/56 is merged and released. 
Same unit test passes now after this change. 

Initialize ephemeralProperties in NewFContext

---

.travis.yml

INFENG-8047 Remove pypi url env variable, as twine defaults to the correct one.

---

lib/java/src/main/java/com/workiva/frugal/transport/FNatsTransport.java
lib/java/src/test/java/com/workiva/frugal/transport/FNatsTransportTest.java

transport.close() does not call connection.close(dispatcher) which causes it to leak a thread.
TODO
TODO
TODO

call close dispatcher to prevent thread leak

---

compiler/generator/java/generator.go
test/expected/java/actual_base/FBaseFoo.java
test/expected/java/boxed_primitives/FFoo.java
test/expected/java/deprecated_logging/FFoo.java
test/expected/java/valid_vendor/FMyService.java
test/expected/java/valid_vendor/MyScopePublisher.java
test/expected/java/valid_vendor/MyScopeSubscriber.java
test/expected/java/valid_vendor_no_path/FMyService.java
test/expected/java/valid_vendor_no_path/MyScopePublisher.java
test/expected/java/valid_vendor_no_path/MyScopeSubscriber.java
test/expected/java/variety/EventsPublisher.java
test/expected/java/variety/EventsSubscriber.java
test/expected/java/variety/FFoo.java
test/expected/java/variety_async/FFoo.java
test/expected/java/vendored_but_no_use_vendor/FMyService.java
test/expected/java/vendored_but_no_use_vendor/FVendoredBase.java
test/expected/java/vendored_but_no_use_vendor/MyScopePublisher.java
test/expected/java/vendored_but_no_use_vendor/MyScopeSubscriber.java

When trying to add a middleware to `FScopeProvider` in messaging-sdk, I ran the service and hit this error
```
Exception in thread "UserSync" java.lang.UnsupportedOperationException
at java.util.AbstractList.add(AbstractList.java:148)
at java.util.AbstractList.add(AbstractList.java:108)
at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
at com.workiva.frugal.event_framework.v1.events.EventSubscriber$Client.<init>(EventSubscriber.java:100)
at com.workiva.graph.userSync.IdentitySubscriber.subscribe(IdentitySubscriber.java:69)
at com.workiva.graph.userSync.UserSync.run(UserSync.kt:26)
at com.workiva.graph.userSync.Main$main$1.invoke(Main.kt:29)
at com.workiva.graph.userSync.Main$main$1.invoke(Main.kt:17)
at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
``` …

Fix ArrayList type

---

compiler/generator/dartlang/generator.go
test/expected/dart/actual_base/f_nested_thing.dart
test/expected/dart/actual_base/f_thing.dart
test/expected/dart/include_vendor/f_my_service_service.dart
test/expected/dart/include_vendor/f_vendored_references.dart
test/expected/dart/variety/f_awesome_exception.dart
test/expected/dart/variety/f_event.dart
test/expected/dart/variety/f_event_wrapper.dart
test/expected/dart/variety/f_foo_args.dart
test/expected/dart/variety/f_foo_service.dart
test/expected/dart/variety/f_test_base.dart
test/expected/dart/variety/f_test_lowercase.dart
test/expected/dart/variety/f_testing_defaults.dart
test/expected/dart/variety/f_testing_unions.dart

Sometimes field names defined in users IDLs can collide with variables names the dart generator uses. We should reference variable names with a `this.` when appropriate to avoid that.
@Workiva/product2 @todbachman-wf

INFENG-9206 use "this." for fields when possible

---

scripts/update.py

We're going to start tagging frugal with the v prefix to make go mod happy. When we update all the files we don't want the v to get added.
TODO
```
python scripts/update.py --version v3.4.9
```
TODO

INFENG-9265 Ignore the v prefix on tags

---

lib/python/frugal/tornado/transport/http_transport.py

The underlying tornado http client has it's own limits that need to be set. We set those to be the frugal limits if one is provided. We decided to not pass any max/mins if zero is provided as we don't have a good default to set.
@Workiva/product2 
@joestrach-wf If you want to test this too that would be great. I did a couple simple scenarios locally and it seemed like it worked

INFENG-9530 set buffer sizes on tornado http transport

---

Dockerfile
lib/dart/pubspec.yaml
lib/dart/test/transport/f_adapter_transport_test.dart
lib/dart/test/transport/f_http_transport_test.dart
scripts/smithy/smithy_dart.sh
skynet.yaml
test/integration/dart/test_client/pubspec.yaml

Frugal still uses dart1 in both workiva-build and skynet. Switch to dart2. 
TODO
CI passes.
CI passed.

INFENG-9845: Remove dart1 in CI

---

Dockerfile
scripts/skynet/skynet_setup.sh
scripts/skynet/test_cleanup.sh
skynet.yaml

Consume messaging-docker-image 0.0.39 (updates dart to 2.6.1 and nats-server to 2.1.2)
CI passes

INFENG-10121: Consume messaging-docker-image 0.0.39

---

lib/python/frugal/context.py

The docstrings for the python context timeouts had incorrect units. Fix it.

Update python context timeout docstrings to reflect the correct units

---

compiler/generator/dartlang/generator.go
test/expected/dart/actual_base/f_base_foo_service.dart
test/expected/dart/include_vendor/f_my_service_service.dart
test/expected/dart/variety/f_foo_service.dart
test/expected/dart/vendor_namespace/f_vendored_base_service.dart

Fixes a missing import location for dart generated code from a previous change

add collection import to service files

---

compiler/generator/dartlang/generator.go
test/expected/dart/include_vendor/f_vendored_references.dart
test/expected/dart/variety/f_testing_defaults.dart
test/expected/go/slim/f_types.go
test/expected/go/variety/f_types.txt
test/expected/gopherjs/variety/f_types.go
test/expected/html/standalone/variety.html
test/expected/html/variety.html
test/expected/java/boxed_primitives/TestingDefaults.java
test/expected/java/variety/TestingDefaults.java
test/expected/python.asyncio/variety/ttypes.py
test/expected/python.tornado/variety/ttypes.py
test/expected/python/variety/ttypes.py
test/idl/variety.frugal

(Reopens #1168 targeting `develop` branch.)
The expected enum type for fields is not easily discoverable in generated Dart code.  Add a dartdoc reference to the enum type.

dart: Add dartdoc reference for enum field type

---

compiler/compiler.go
compiler/generator/generator.go
compiler/generator/json/generator.go
documentation/json.md
test/expected/frugal.json
test/json_test.go

We would like to be able to introspect Frugal files without the complexity of actually parsing the Frugal file format.
A new `-gen json` output mode is added that produces a lightweight JSON format.  The key names are deliberately kept short to minimize the size of the file since we would like to use the output in very space-constrained storage where compression is not an option.
Unit test added for `variety.frugal`.

Add JSON generator

---

.travis.yml
Makefile

Travis was failing originally installing virtualenv from pip. I fixed that by using the apt package for virtualenv and updated to the bionic image (not related, but seemed like a good idea). 
Next, java checkstyle was failing because openjdk 11 and maven are now baked into the go image and apt installing openjdk8 doesn't update the `JAVA_HOME` for some reason. So checkstyle and javadoc were failing - it looks like there are known bugs with those and certain versions of jdk 11. I started down the rabbit hole of updating those but the PR started to blow up, so I opted to just pin to jdk 8 for now.

Fix Travis CI Build

---

.dependabot/config.yml
.travis.yml
Makefile

Setup depandabot to auto PR bumps for library dependencies. Tested by adding these configs using the dependabot dashboard on [my fork](https://github.com/charliestrawn/frugal/pulls). The yml config is a bit different, but I think this matches. It opened about 37 PRs, but I believe dependabot limits it to 10 open at a time by default.

Dependabot config

---

examples/java/pom.xml
lib/java/checkstyle.xml
lib/java/pom.xml

In order to not bombard the repo with PRs, I rolled up the dependency bumps that dependabot will make for java. I closed them on my personal fork as I went through them as you can see [here](https://github.com/charliestrawn/frugal/pulls?q=is%3Apr+is%3Aclosed+label%3Ajava+label%3Adependencies). In order to get the build to pass I had to disable failing on checkstyle violations. I'm not sure if these were just warnings before or if they are just new style guidelines, but I think they probably warrant a follow up PR.

Bump java deps

---

lib/java/src/main/java/com/workiva/frugal/transport/FHttpTransport.java
lib/java/src/test/java/com/workiva/frugal/transport/FHttpTransportTest.java

Large HTTP response bodies put pressure on GC due too too many large array allocations.
Tested Java client to Java server and Java client to Go server in an existing codebase.

java: Reduce allocations for FHttpTransport

---

Dockerfile
skynet.yaml

Consumes https://github.com/Workiva/messaging-docker-images/pull/64 to use dart 2.7.1 in workiva-build and skynet
See https://workiva.slack.com/archives/CEDM9RH1N/p1583441797182700 and https://workiva.slack.com/archives/CEDM9RH1N/p1583444094186500
Workiva build and skynet pass

Consume messaging-docker-images 0.1.2

---

compiler/generator/dartlang/generator.go
examples/dart/gen-dart/v1_music/lib/src/f_album_winners_scope.dart
examples/dart/gen-dart/v1_music/lib/src/f_store_service.dart
test/expected/dart/actual_base/f_base_foo_service.dart
test/expected/dart/include_vendor/f_my_scope_scope.dart
test/expected/dart/include_vendor/f_my_service_service.dart
test/expected/dart/variety/f_events_scope.dart
test/expected/dart/variety/f_foo_service.dart
test/expected/dart/vendor_namespace/f_vendored_base_service.dart

As part of a new client side messaging api proposed in [RFD 274](https://sandbox.wdesk.com/a/QWNjb3VudB82NzE5NTMwMjcyOTQ4MjI0/doc/4a01314bdff4427ebe7d639867a12b8c/r/-1/v/1/sec/4a01314bdff4427ebe7d639867a12b8c_28), consumers supply a factory to the client creation methods to allow the messaging-sdk to construct an instance of their frugal class, obviating the need for some extra boilerplate. 
This PR adds this factory to the dart frugal generation, so consumers get the factory boilerplate for free.
TODO
TODO
TODO

CPLAT-10183: Add factories for creating dart frugal objects

---

compiler/generator/dartlang/generator.go
examples/dart/gen-dart/v1_music/lib/src/f_album_winners_scope.dart
examples/dart/gen-dart/v1_music/lib/src/f_store_service.dart
test/expected/dart/actual_base/f_base_foo_service.dart
test/expected/dart/include_vendor/f_my_scope_scope.dart
test/expected/dart/include_vendor/f_my_service_service.dart
test/expected/dart/variety/f_events_scope.dart
test/expected/dart/variety/f_foo_service.dart
test/expected/dart/vendor_namespace/f_vendored_base_service.dart

#1228 added factories for dart objects, but these factories didn't specify a return type. To be explicit and safe, we should specify a return type. 
Also, since the factories are methods, they should start with a lower case.
TODO
TODO
TODO

CPLAT-10346: Add types to frugal factories

---

examples/dart/web/client.dart
lib/dart/lib/src/frugal/transport/f_http_transport.dart
lib/dart/test/transport/f_http_transport_test.dart
test/integration/dart/test_client/bin/main.dart

CPLAT is preparing to release v4 of w_transport soon and this repo contains at least one usage of a deprecated API that will be removed in v4.
This PR includes automated changes from a codemod script to address these deprecated API usages.
At least one of the following changes have been made:
```diff
- import 'package:w_transport/w_transport_browser.dart';
+ import 'package:w_transport/browser.dart';
```
```diff
- import 'package:w_transport/w_transport_mock.dart';
+ import 'package:w_transport/mock.dart';
```
```diff
- import 'package:w_transport/w_transport_vm.dart';
+ import 'package:w_transport/vm.dart';
```
```diff
- Client
+ HttpClient
```
The changes made by this automated script are all drop-in replacements, meaning they should not require any additional changes to function …

Updates for w_transport v4 compatibility

---

compiler/generator/dartlang/generator.go
examples/dart/gen-dart/v1_music/lib/src/f_store_service.dart
examples/dart/gen-dart/v1_music/pubspec.yaml
lib/dart/lib/src/frugal/f_provider.dart
test/expected/dart/actual_base/f_base_foo_service.dart
test/expected/dart/include_vendor/f_my_service_service.dart
test/expected/dart/include_vendor/pubspec.yaml
test/expected/dart/variety/f_foo_service.dart
test/expected/dart/vendor_namespace/f_vendored_base_service.dart

When using a frugal object to RPCs, the consumer must open and close an `FAsyncTransport` object manually. That object is actually disposable, so we can update the `dispose` method on it to close the transport, which will be done for Workiva private code as part of [CPLAT-9647](https://jira.atl.workiva.net/browse/CPLAT-9647). That work need not be completed before this merges, however, as `FNatsTransport` is already disposable so managing it here will have no harm.
After creation, the only reference to this transport persists in the `FServiceProvider` instance, which is then passed to the frugal client. This PR changes this so we manage the disposal of `FNatsTransport` in the `FServiceProvider` class and manage the disposable of `FServiceProvider` in the frugal generated client code. …

CPLAT-10353: Manage frugal service objects

---

compiler/generator/dartlang/generator.go
examples/dart/gen-dart/v1_music/lib/src/f_store_service.dart
examples/dart/gen-dart/v1_music/pubspec.yaml
lib/dart/lib/src/frugal.dart
lib/dart/lib/src/frugal/f_provider.dart
lib/dart/pubspec.yaml
test/expected/dart/actual_base/f_base_foo_service.dart
test/expected/dart/include_vendor/f_my_service_service.dart
test/expected/dart/include_vendor/pubspec.yaml
test/expected/dart/variety/f_foo_service.dart
test/expected/dart/vendor_namespace/f_vendored_base_service.dart

In #1239, the `FServiceProvider` began managing the `transport` it was given. This was released in Frugal 3.9.1, and it broke tests for some downstream consumers which were instantiating `FServiceProvider` using null & mock objects.
This was reverted in Frugal 3.9.2. 
This re-implements the work in #1239, but also guards against managing mock or null objects, or objects which are already disposing. 
TODO
* Run tests in several major product repos internal to Workiva with/without re-generating some of the client frugal code
* Smoke test running the application in at least one major product repo internal to Workiva with/without re-generating some of the client frugal code.
TODO

CPLAT-10449: Add check before calling `manageDisposable`

---

compiler/generator/dartlang/generator.go
examples/dart/gen-dart/v1_music/lib/src/f_store_service.dart
examples/dart/gen-dart/v1_music/pubspec.yaml
lib/dart/lib/src/frugal.dart
lib/dart/lib/src/frugal/f_provider.dart
test/expected/dart/actual_base/f_base_foo_service.dart
test/expected/dart/include_vendor/f_my_service_service.dart
test/expected/dart/include_vendor/pubspec.yaml
test/expected/dart/variety/f_foo_service.dart
test/expected/dart/vendor_namespace/f_vendored_base_service.dart

#1249 added safeguards to prevent sending a `Mock` object to `manageDisposable`. This was nested references on the `Mock` objects were accessed in `manageDisposable`, which would throw an error since the first nested getter would return `null`. 
The solution, however, requires testing for a `Mock` object, which requires access to the mockito package in production code. This is undesirable, since that package is meant just for testing. 
This change moves the disposal to `onDispose` and calls `dispose()` directly on the disposable objects. We safeguard in the case where the object is already disposing, or is not a `Disposable`. In the case where the object is a `Mock`, the call to `dispose()` is a no-op, since it's at the top level of the parent object.
TODO
* Run tests with/without …

CPLAT-10460: Leverage onDispose to avoid difficulties with mock objects

---

lib/dart/lib/src/frugal/f_error.dart
lib/go/errors.go
lib/gopherjs/frugal/errors.go
lib/java/src/main/java/com/workiva/frugal/exception/TTransportExceptionType.java
lib/java/src/main/java/com/workiva/frugal/transport/FNatsPublisherTransport.java
lib/java/src/main/java/com/workiva/frugal/transport/FNatsTransport.java
lib/java/src/test/java/com/workiva/frugal/transport/FNatsPublisherTransportTest.java
lib/java/src/test/java/com/workiva/frugal/transport/FNatsTransportTest.java
lib/python/frugal/exceptions.py

Commits are intended to be reviewed independently. See commit messages for details.
I had previously discussed adding a `RECONNECTING` option, but I think `DISCONNECTED` makes more sense since "reconnecting" is really a sub-state of "disconnected".
I don't have the expertise to implement similar changes for the other languages, so I have simply reserved an exception type number.
I manually tested as part of a service that does frequent publishes.  I stopped NATS and was able to verify the new type was used.

java: Add TTransportExceptionType.DISCONNECTED

---

lib/java/src/main/java/com/workiva/frugal/server/FDefaultNatsServerEventHandler.java
lib/java/src/main/java/com/workiva/frugal/server/FDefaultServerEventHandler.java
lib/java/src/main/java/com/workiva/frugal/server/FServlet.java
lib/java/src/test/java/com/workiva/frugal/server/FServletTest.java

See commit messages for details.  In particular, the third commit:
> Submitting to an ExecutorService is an easy way to limit concurrency
> differently on a per-endpoint basis rather than relying on the global
> shared HTTP thread pool.  Additionally, this also allows the same
> concurrent limits to be applied if the service handler is exposed by
> multiple servers (for example, NATS and HTTP).  Finally, this also makes
> it easy to specify meaningful service thread names rather than using
> generic HTTP pooled thread names.  This could be extended in the future
>  to use the asynchronous servlet mechanism so the HTTP thread can be
> reused while the Frugal thread is still processing.
Commits are intended to be designed independently.
I've manually tested on an internal service using HTTP …

INFENG-11584: java: Support custom ExecutorService on a per-FServlet basis

---

lib/java/src/main/java/com/workiva/frugal/transport/FNatsTransport.java
lib/java/src/test/java/com/workiva/frugal/transport/FNatsTransportTest.java

I considered adding `protected TException getRequestTimeoutException` to `FAsyncTransport` rather than creating a separate wrapping exception.  This approach avoided new API and wasn't significantly more complicated.
Already manually included in a client and tested using an internal service in order to produce the sample stack traces.

java: Improve NATS timeout exception

---

compiler/generator/dartlang/generator.go
examples/dart/gen-dart/v1_music/lib/v1_music.dart
test/expected/dart/actual_base/actual_base_dart.dart
test/expected/dart/include_vendor/include_vendor.dart
test/expected/dart/variety/variety.dart
test/expected/dart/vendor_namespace/vendor_namespace.dart

Dart generated frugal factories for clients and scopes were not publicly exported from the generated entrypoint. 
This updates the frugal compiler to expose those factories from the generated entrypoint.
N/A
CI Passes (tests updated)
N/A

CPLAT-11680: Expose frugal client scope factories

---

compiler/parser/types.go
test/audit_test.go
test/common_test.go
test/idl/bad_op_type.frugal
test/idl/breaking_changes/scope7.frugal
test/invalid_test.go

If a scope operation references an invalid include, the generator currently crashes.  (As an aside, the `recover` makes it rather difficult to diagnose.  It seems like the tool should just handle all cases rather than giving a vague error message when it crashes...)
Commits are intended to be reviewed independently
cc: @justinlindh-wf

Fix scope operation type error

---

examples/java/pom.xml
lib/java/pom.xml
lib/java/src/main/java/com/workiva/frugal/provider/FServiceClient.java
lib/java/src/test/java/com/workiva/frugal/provider/FServiceClientTest.java
test/integration/java/frugal-integration-test/pom.xml

Pulling in thrift 0.13.0 to patch CVE's.  Successor to #1337
CVE-2019-0210
CVE-2019-0205
CVE-2018-1320
Update was broken into 2 PRs, if moving to 0.13.0 is to much, consider generating code with frugal v3.10.0 first, then attempting the upgrade.
Run the java examples with old and new service client configurations.
| Server Thrift Version | Client Thrift Version | Status |
|--------|-------|-------|
| v0.9.3 | v0.9.3 | ??? |
| v0.9.3 | v0.13.0 | ??? |
| v0.13.0 | v0.9.3 | ??? |
| v0.13.0 | v0.13.0 | ??? |

Thrift 0.13.0

---

lib/java/pom.xml

Fixes mvn package to be usable by JDKs greater than 1.8
TODO
TODO
TODO

Fixes mvn package to be usable by JDKs greater than 1.8

---

examples/go/glide.yaml
lib/go/adapter_transport.go
lib/go/client.go
lib/go/client_test.go
lib/go/context.go
lib/go/framed_transport.go
lib/go/framed_transport_test.go
lib/go/go.mod
lib/go/processor.go
lib/go/processor_test.go
lib/go/transport_monitor_test.go

We took what we learned from https://github.com/Workiva/frugal/pull/1350 (pre v3.10.1)
Applied it to v3.10.1 code generator https://github.com/Workiva/frugal/pull/1352 so generated code shouldn't break.
Consume both changes on develop, and roll out with thrift 0.13.0 support!
Changing go Interfaces in Thrift 0.13.0
```diff
type TTransport interface {
-	Flush() error
+	Flush(ctx context.Context) error
// ... other fields omitted ...
}
type TTransportFactory interface {
-	GetTransport(trans TTransport) error
+	GetTransport(trans TTransport) (TTransport, error)
}
type TApplicationException interface {
-	Read(iprot TProtocol) (TApplicationException, error)
+	Read(iprot TProtocol) error
// ... other fields omitted ...
}
```
See previous PRs for details, but essentially, previous work was done …

SPLAT-189: Go: Thrift 0.13.0

---

.travis.yml

Looks like glide was renamed golang-glide sometime in the past week or so.
*EDIT: our `ubuntu-latest` runners must have been updated*
> On Ubuntu Zesty (17.04) the package is called golang-glide.
> Source: https://salsa.debian.org/go-team/packages/golang-glide
*EDIT(2): Looks like `ppa:masterminds/glide` was experiencing some network issues; swapping to default apt repository.*
```
$ sudo add-apt-repository -y ppa:masterminds/glide
// ... snipped ...
Reading package lists...
W: Failed to fetch http://ppa.launchpad.net/masterminds/glide/ubuntu/dists/bionic/main/binary-i386/Packages  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out [IP: 91.189.95.83 80]
W: Failed to fetch http://ppa.launchpad.net/masterminds/glide/ubuntu/dists/bionic/main/binary-amd64/Packages …
```

SPLAT-196: Drop glide dep in Travis

---

lib/python/requirements_dev_asyncio.txt

Looks like a recent version of aiohttp broke the mock usage. Version 3.7.2 break, pinning back to 3.6.2/3.6.3 to see if that resolves for the short-term.
TODO
TODO
TODO

SPLAT-382: aiohttp issues

---

.travis.yml
Dockerfile
lib/go/frugal_test.go
lib/go/http_transport_test.go
lib/gopherjs/frugal/frugal_js.go
lib/gopherjs/frugal/frugal_test.go
lib/gopherjs/thrift/simple_json_js.go
test/integration/readme.md

Currently several repos are locked into Go <=1.12 because they depend on [gopherjs](https://github.com/gopherjs/gopherjs), which is no longer under active development. We have decided to adopt the [goplusjs fork of gopherjs](https://github.com/goplusjs/gopherjs), which supports Go >=1.13.
This PR updates this repo to consume Go1.15 and switches us over to the goplusjs fork of gopherjs.
All consumers of gopherjs have been updated to build their bindings and run their tests with the goplusjs fork (or, in a few cases, will be very shortly). 
Verify that this can be consumed by a library consuming goplusjs should be sufficient. A passing build in [DPC](https://github.com/Workiva/doc_plat_client/pull/11770) may be sufficient, but I will defer to repo maintainers if they would like further …

Consume Go 1.15 and goplusjs fork of gopherjs

---

Makefile
compiler/generator/dartlang/generator.go
lib/dart/lib/frugal.dart
lib/dart/lib/src/frugal/f_packers.dart
lib/go/go.mod
test/expected/dart.nullunset/actual_base/f_base_foo_service.dart
test/expected/dart.nullunset/variety/f_foo_service.dart
test/expected/dart/actual_base/f_base_foo_service.dart
test/expected/dart/include_vendor/f_my_service_service.dart
test/expected/dart/variety/f_foo_service.dart
test/expected/dart/vendor_namespace/f_vendored_base_service.dart

The dart generated code is very verbose, more so than the go version. In go, prepareMessage and processReply are shared and generic. Update the dart generation to reflect that behavior. 
Pull repeated code out of the dart functions and into a shared member. Reduce the total file size of each service provider. 
I ran this against DPC here to verify the behavior against many services. https://github.com/Workiva/doc_plat_client/pull/12635.
With the latest changes, this is less straight forward and requires the dart dep to be upgraded before you can use it. As a result the PR no longer passes CI. 
This reduced the total line count in DPC by ~4000 lines and reduced the generated js size. I would expect the same to apply on a grander scale to all of workiva's dart code. 

CT-29  Share packing and unpacking code in dart generated files

---

lib/java/pom.xml
lib/java/src/main/java/com/workiva/frugal/server/FJakartaServlet.java
lib/java/src/test/java/com/workiva/frugal/server/FJakartaServletTest.java

See commit message.
There is little room for code sharing between the two servlet implementations (the accesses to `javax.servlet`/`jakarta.servlet` types is spread throughout the class).  Ultimately, these classes don't change much, so I concluded it was easier to simply copy.
Temporarily update `TestServletServer` to use Jetty 11 and `FJakartaServlet`.  There can only be one dependency on Jetty in the integration test, and 9->11 is a breaking change for javax->jakarta, so it's non-trivial to automate.
Manually tested with an existing service using Jetty 9 with `FServlet` and confirmed it works the same after upgrading to Jetty 11 and the `FJakartaServlet`

java: Add FJakartaServlet

---

scripts/lang/go.py
scripts/update.py

update.py script failing do to transition from godep/glide to gomod.
N/A
- Run `python scripts/update.py --version v3.14.0` on this branch and review changes to versions.
```
$ python scripts/update.py --version v3.14.0
dict_keys(['dart', 'go', 'java', 'python'])
Updating frugal to version 3.14.0 for dart, go, java, python
Events: scope subscriber generation is not implemented for vanilla Python 2.7. For 2.7, use the Tornado framework (where available) or provide a pull request
Events: scope subscriber generation is not implemented for vanilla Python 2.7. For 2.7, use the Tornado framework (where available) or provide a pull request
PASS
ok  	github.com/Workiva/frugal/test	48.138s
Updating expected tests for dart
Updating expected tests for go
Updating expected tests for java
Updating …
```

Fix update.py for Go

---

lib/dart/lib/src/frugal/transport/f_async_transport.dart

Doing so just leads to an unhandled exception
As a consumer, we see these sometimes:
```
exception: { [-]
message: Uncaught exception during experience runtime
stacktrace: org-dartlang-sdk:                                                                                                                                  _AsyncCompleter.complete
https://cdn-prod.wdesk.com/wdesk/packages/frugal/src/frugal/transport/f_async_transport.dart 104:5                                                 FAsyncTransport.handleResponse
https://cdn-prod.wdesk.com/wdesk/packages/messaging_sdk/src/internal/transport/f_nats_transport.dart 150:13                                        FNatsTransport._open.<anonymous function>
org-dartlang-sdk: …
```

SPLAT-1140 Dart: Don't complete already-completed completers

---

lib/dart/lib/src/frugal/f_error.dart
lib/go/errors.go
lib/java/src/main/java/com/workiva/frugal/exception/TTransportExceptionType.java
lib/java/src/main/java/com/workiva/frugal/transport/FAsyncTransport.java
lib/java/src/main/java/com/workiva/frugal/transport/FHttpTransport.java
lib/java/src/main/java/com/workiva/frugal/transport/FNatsTransport.java
lib/java/src/test/java/com/workiva/frugal/transport/FAsyncTransportTest.java
lib/java/src/test/java/com/workiva/frugal/transport/FHttpTransportTest.java
lib/java/src/test/java/com/workiva/frugal/transport/FNatsTransportTest.java
lib/python/frugal/exceptions.py

Commits are intended to be reviewed independently.  See commit messages for details.
I was developing an integration test issue where a Frugal request was being sent to a subject with no responders, and I was receiving the following exception in the logs:
```
java.lang.IllegalArgumentException: 4 > 0
at java.base/java.util.Arrays.copyOfRange(Arrays.java:4029)
at com.workiva.frugal.transport.FNatsTransport$Handler.onMessage(FNatsTransport.java:147)
at io.nats.client.impl.NatsDispatcher.run(NatsDispatcher.java:98)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at …
```

java: Fix spurious IllegalArgumentException with NATS 2.2.0 and no responders

---

lib/go/nats_scope_transport.go

Need to add support for parallel workers for processing subscription messages.
Added a `FNatsSubscriberFactoryBuilder` similar to `FNatsServerFactoryBuilder`
Worker queue logic is also similar to the nats server worker queue logic
Modified vessel code examples to process messages too slowly with a single worker. Then updated the subscriber to use multiple workers. 
Regardless of worker count all messages were processed. With a higher worker count it was able to process more messages.

add workers to fNatsSubscriberTransport

---

lib/dart/pubspec.yaml
test/integration/dart/test_client/pubspec.yaml

In order for projects to be compatible with Dart 2.13, there are dependencies that need to have their ranges widened. 
For a list of dependencies expected to be changed, see the dependencies section of the Dart 2.12+ [wiki page](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=189370832).
Another necessary change is the removal of `build_vm_compilers`. If this is the case, additional clean up may need to be done, such as removing the associated config from `build.yaml` or updating how tests are run. A member of Client Platform will be following up with PRs that have CI failures to resolve any issues or perform necessary clean up.
For any questions or concerns, don't hesitate to reach us in the #support-client-plat Slack channel!
- Update specific dependencies to be compatible …

Widen Dependency Ranges Blocking Dart 2.13

---

lib/python/setup.py

New version of aiohttp imcompatible with current dependency setup.

SPLAT-2065: Pin aiohttp to <3.8.0

---

skynet.yaml

https://jira.atl.workiva.net/browse/CID-1062
The [skynet.yaml specification](https://github.com/Workiva/skynet/blob/master/docs/skynet/getting-started/skynet-yaml.md#during-a-production-release) includes a concept
named on-promotion that originates from a process that the now shut down service Shipyard managed.
Since that shut down, Workiva has shifted to performing actions on tags and the newer on-tag field was added to reflect that.
The behavior of the tests are identical when using on-promotion and on-tag today.
[CID](https://github.com/Workiva/cid) will no longer support the deprecated on-promotion trigger, so repositories
will need to have it replaced before the eventual transition.
Please reach out to `#support-test` or `#support-cid` with any questions.
[_Created by Sourcegraph …

Update the on-promotion trigger to on-tag in skynet.yaml.

---

Dockerfile
scripts/skynet/cross/setup_java.sh
skynet.yaml

https://jira.atl.workiva.net/browse/CID-947
The BUILD_ARTIFACTS_ARTIFACTORY build arg has been deprecated and replaced/made synonymous with BUILD_ARTIFACTS_JAVA as
noted in the workiva-build [user guide](https://github.com/Workiva/workiva-build/blob/master/doc/user_guide.md#artifacts)
[CID](https://github.com/Workiva/cid) will no longer support the deprecated BUILD_ARTIFACTS_ARTIFACTORY, so repositories
will need to have it replaced before the eventual transition.
Please reach out to `#support-cid` or `#support-build` with any questions.
[_Created by Sourcegraph batch change `Workiva/remove_deprecated_build_args`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/remove_deprecated_build_args)

Update the deprecated build arg BUILD_ARTIFACTS_ARTIFACTORY to BUILD_ARTIFACTS_JAVA.

---

lib/dart/pubspec.yaml

Client Platform is updating dependencies. More info: 
This PR raises the max version allowed for w_transport to <5.0.0
```
pubspec_codemod raise-max w_transport 5.0.0 --recursive
pubspec_codemod raise-min messaging_sdk 3.17.0 --recursive
pubspec_codemod raise-min wdesk_sdk 2.303.71 --recursive
```
For more info, reach out to `#support-client-plat` on Slack.
[_Created by Sourcegraph batch change `Workiva/w_transport_v4_raise_max`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/w_transport_v4_raise_max)

Raise w_transport max to <5.0.0

---

compiler/generator/dartlang/generator.go
compiler/testdata/expected/dart.nullunset/include_vendor/pubspec.yaml
compiler/testdata/expected/dart/include_vendor/pubspec.yaml
examples/dart/gen-dart/v1_music/pubspec.yaml
examples/dart/pubspec.yaml
lib/dart/pubspec.yaml
test/integration/dart/gen-dart/frugal_test/pubspec.yaml

Summary
---
Client Platform is updating dependencies! More details at
This batch raises the max versions allowed for the following
dependencies:
- args <3.0.0
- build <3.0.0
- build_config <2.0.0
- build_runner <3.0.0
- checked_yaml <3.0.0
- logging <2.0.0
- pub_semver <3.0.0
- pubspec_parse <2.0.0
- uri <2.0.0
For more info, reach out to `#support-client-plat` on Slack.
[_Created by Sourcegraph batch change `Workiva/raise_max_versions`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/raise_max_versions)

Raise Max Versions

---

lib/java/pom.xml
lib/java/src/main/java/com/workiva/frugal/protocol/FProtocol.java
lib/java/src/main/java/com/workiva/frugal/server/FNatsServer.java
lib/java/src/main/java/com/workiva/frugal/server/FSimpleServer.java
lib/java/src/main/java/com/workiva/frugal/transport/TFramedTransport.java
lib/java/src/main/java/com/workiva/frugal/transport/TMemoryOutputBuffer.java
lib/java/src/test/java/com/workiva/frugal/transport/TMemoryOutputBufferTest.java
test/integration/java/frugal-integration-test/pom.xml

There were some change to some of the Thrift Interfaces to add some additional method. 
* FProtocol is mostly a straight pass through to TProtocol
* TFramedTransport is a straight pass through to TTransport
* TMemoryOutputBuffer on the other hand was rebased to TEndpointTransport to support the default implementations of the missing abstract methods on TTransport, this also caused some exception handle propagation to FNatsServer

Updgrade thrift to 0.14.2 to avoid cve

---

lib/python/frugal/aio/server/nats_server.py
lib/python/frugal/aio/transport/nats_scope_transport.py
lib/python/frugal/aio/transport/nats_transport.py
lib/python/frugal/tests/aio/server/test_nats_server.py
lib/python/frugal/tests/aio/transport/test_nats_scope_transport.py
lib/python/frugal/tests/aio/transport/test_nats_transport.py
lib/python/requirements_dev_asyncio.txt
lib/python/setup.py

For python 3.10 support it was requested that we upgrade from async-nats-client v0.11.5 to nats-py v2.0 or higher
https://github.com/orgs/Workiva/teams/service-platform

MEX-124: Frugal - Upgrade async-nats-client to 2.x

---

lib/dart/lib/src/frugal/f_context.dart
lib/go/context.go
lib/java/src/main/java/com/workiva/frugal/FContext.java
lib/python/frugal/context.py

Document our current understanding for best practices around reusing/mutating FContext.
CI only.  Doc only change.
@ryanjackson-wf 
@patkujawa-wf 
@robbecker-wf

Document best practices for FContext reuse

---

.github/dependabot.yaml
examples/java/pom.xml
lib/java/pom.xml
test/integration/java/frugal-integration-test/pom.xml

Breaking changes in slf4j v2 broke consumers, e.g. https://github.com/Workiva/markup-service/pull/1009. Revert back to v1 and prevent automated major version bumps by dependabot.
- [NA] Unit tests have been updated
- [NA] Updates to documentation if necessary
Verify that the version in the build artifacts is 1.7.36 again.
```
[patkujawa@wf16264 Fri Sep  9 11:46:33 MDT 2022] ~/workspace/frugal (revert_slf4j_v2)
❯ mvn dependency:tree -Dincludes=org.slf4j -f lib/java/pom.xml
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] -------------------------< com.workiva:frugal >-------------------------
[INFO] …
```

Revert slf4j v2 upgrade and skip major version upgrades in dependabot

---

compiler/generator/dartlang/generator.go
compiler/testdata/expected/dart.nullunset/include_vendor/pubspec.yaml
compiler/testdata/expected/dart/include_vendor/pubspec.yaml
examples/dart/gen-dart/v1_music/pubspec.yaml
lib/dart/pubspec.yaml
test/integration/dart/gen-dart/frugal_test/pubspec.yaml

Summary
---
This update will allow w_common 2x by raising the max to < 3.0.0
It also raises the minimum of a few packages that addressed w_common
v2 breaking changes. In order to be compatible with w_common v2, we
need at least these versions.
dart_dev_workiva 1.5.9
wdesk_sdk 3.7.8
w_router 1.1.15
w_flux 2.10.21
w_module 2.0.30
bigsky_rest_files 1.33.10
In addition, sass compilation was moved out of w_common into a 
w_common_tools package, so if it detects that the repo might need it, 
it might add a dependency on w_common_tools.
Lastly, app/pubspec.lock files may have needed to be updated to get 
those minimum versions of packages
For more info, reach out to …

w_common v2 rollout - 1 of 2 raise max

---

scripts/smithy/smithy_python.sh

importlib-metadata 5.0.0 deprecated EntryPoints (https://exerror.com/entrypoints-object-has-no-attribute-get/#:~:text=facing%20this%20error.-,To%20Fix%20'EntryPoints'%20object%20has%20no%20attribute%20'get',Your%20error%20will%20be%20solved.)
Pinning supported version for now.
N/A
CI Passes
N/A

SPLAT-4559: Pin importlib-metadata==4.13.0

---

lib/java/pom.xml
test/integration/java/frugal-integration-test/pom.xml

We had a few people with projects that included frugal only as a secondary dependency complain that their builds were failing due to gson being a tertiary dependency, but it seems we aren't actually using it anywhere. 
Removing.

Remove gson dependency

---

lib/python/Makefile
lib/python/py2_reqs/requirements_python_2.txt
lib/python/requirements_dev_common.txt
lib/python/requirements_python_3.txt

Python 2 compatibility surfacing in newer versions of packages. Add split supported mock version, move req file for python 2 to directory to avoid dependabot bumps.
@Workiva/service-platform @ivanvandessel-wk

Add split mock versions, move py2 reqs file

---

.github/dependabot.yaml

Get dependabot to ignore updating dependencies for python2 libraries that can not be moved forward
python2 dependent libraries can not be updated like python3 can so we split them out and I am ignoring those versions in dependabot yaml file
tests in skynet pass

update to ignore dependabot updates for python2 library dependencies

---

.github/dependabot.yaml

fix yaml file for dependabot ignoring of python2 libraries
ignoring of python pip env dependencies related to python2 libraries that can not be updated due to not compatible with python2 
skynet tests pass

fix yaml formatting issue

---

lib/java/src/main/java/com/workiva/frugal/server/FServlet.java
lib/java/src/test/java/com/workiva/frugal/server/FServletTest.java

Jakarta EE has [renamed](https://eclipse-foundation.blog/2020/12/08/jakarta-ee-9-delivers-the-big-bang/) all packages to `jakarta.`.  #1410 added `FJakartaServlet` as a replacement.  We would like to remove `FServlet` in the future, so start warning developers that `FServlet` is going away.
N/A.  Deprecation only.

java: Deprecate FServlet

---

lib/dart/pubspec.yaml

Summary
---
This will require analyzer 1.7.2+ and now that we're past analyzer 1.7.1
we can unpin the meta dependency. (We had restricted it to <1.7.0 in many places)
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/analyzer1_unpin_meta`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/analyzer1_unpin_meta)

Raise analyzer minimum & unpin meta

---

examples/dart/pubspec.yaml

Summary
---
This PR gets us closer to unblocking analyzer 2+ by allowing these new versions
once we upgrade built_redux, over_react, and handle json_serializable.
It raises the maximum for these packages:
- build_web_compilers
- build_test
- build_runner
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/newer_build_dev_deps`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/newer_build_dev_deps)

Allow newer build dependencies

---

lib/dart/pubspec.yaml

Summary
---
We've discovered that mockito 5.3.0 is not compatible with analyzer 2x.
So as we work to get repos upgraded to analyzer 2, mockito will start to fail
to compile. We can avoid this by setting an upper bound to avoid the known bad version.
mockito 5.3.1 and higher are ok, but require analyzer 4+
This batch will change the mockito dependency from ^5.0.0 to `'>=5.0.0 <5.3.0'`
and may add a dependency_validator ignore for the pinned version of mockito
if neccessary.
A passing CI is sufficient QA (means mockito compiles and tests run).
For more info, reach out to Rob Becker in `#support-frontend-dx`
[_Created by Sourcegraph batch change …

Pin mockito 5

---

Dockerfile
skynet.yaml

Consume [messaging-docker-images 0.1.14](https://github.com/Workiva/messaging-docker-images/releases/tag/0.1.14)
Pull Requests included in release:
* Patch changes:
* [Upgrade to Dart 2.18.7](https://github.com/Workiva/messaging-docker-images/pull/78)
Requested by: @rmconsole3-wf
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5198026715955200/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5198026715955200/?repo_name=Workiva%2Ffrugal&pull_number=2149)

Consume messaging-docker-images 0.1.14

---

lib/dart/pubspec.yaml

This PR widens the allowable version ranges of dart_dev so that all repos at Workiva can consume dart_dev 4.0.0 without updating all repositories in lock step.
For more info, reach out to Timothy Steward or `#link23-state-of-the-dart-jam` on Slack.
[_Created by Sourcegraph batch change `Workiva/dart_dev_widen_ranges_v4`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/dart_dev_widen_ranges_v4)

Prepare for dart_dev v4.0.0

---

compiler/generator/dartlang/generator.go
compiler/testdata/expected/dart.nullunset/include_vendor/pubspec.yaml
compiler/testdata/expected/dart/include_vendor/pubspec.yaml
examples/dart/gen-dart/v1_music/pubspec.yaml
lib/dart/pubspec.yaml
test/integration/dart/gen-dart/frugal_test/pubspec.yaml

Summary
---
Frontend Frameworks is updating dependencies!
This update will allow the nullsafe versions of w_common 3x 
by raising the max to < 4.0.0
For more info, visit `#lang-dart` in Slack.
[_Created by Sourcegraph batch change `Workiva/w_common_v3`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/w_common_v3)

w_common v3 rollout - 1 of 2 raise max

---

lib/java/pom.xml

Reverts Workiva/frugal#2148
There was an issue in jnats which is fixed in this PR that has yet to be released:
https://github.com/nats-io/nats.java/pull/874

Revert "java-lib: bump jnats from 2.16.8 to 2.16.9 in /lib/java"

---

.github/dependabot.yaml

Java lib consumption is broken for 3.16.16 due to a jnats issue.
The upstream fix is in https://github.com/nats-io/nats.java/pull/874 but not released yet. Tell dependabot to skip this version.

skip broken version for jnats

---

lib/java/src/main/java/com/workiva/frugal/server/FDefaultNettyHttpProcessor.java

The `FDefaultNettyHttpProcessor.processFrame` method uses a `TMemoryInputTransport` to deserialize incoming Frugal request payloads but doesn't allow to pass in a `TConfiguration` upon its instantiation. As a result we're bound to whatever maximum message size used by `TConfiguration` (currently `100 * 1024 * 1024` bytes). This PR makes it so a custom maximum message size value can be passed to `FDefaultNettyHttpProcessor`.

Allow the customization of the maximum message size in FDefaultNettyHttpProcessor

---

compiler/generator/dartlang/generator.go
compiler/testdata/expected/dart.nullunset/include_vendor/pubspec.yaml
compiler/testdata/expected/dart/include_vendor/pubspec.yaml
examples/dart/gen-dart/v1_music/pubspec.yaml
examples/dart/pubspec.yaml
lib/dart/pubspec.yaml
test/integration/dart/gen-dart/frugal_test/pubspec.yaml

Summary
---
```
pubspec_codemod raise-min built_redux 8.0.0 --recursive
pubspec_codemod raise-min logging 1.0.0 --recursive
pubspec_codemod raise-min glob 2.0.0 --recursive
pubspec_codemod raise-min yaml 3.0.0 --recursive
pubspec_codemod raise-min archive 3.0.0 --recursive
pubspec_codemod raise-min xml 5.0.0 --recursive
pubspec_codemod raise-max io 2.0.0 --recursive
pubspec_codemod raise-max memoize 4.0.0 --recursive
pubspec_codemod raise-min intl 0.17.0 --recursive
pubspec_codemod raise-max intl 0.19.0 --recursive
pubspec_codemod raise-max color 4.0.0 --recursive
```
A passing CI is sufficient QA (means dependencies resolve and tests run and pass).
For more info, …

Update dart dependencies

---

.github/dependabot.yaml

Reset dependabot.yml back since frugal is private repo and cannot access internal secrets.

Revert dependabot changes due to public repo

---

lib/dart/lib/frugal.dart
lib/dart/lib/src/frugal/f_generated.dart

Generated code for Dart is larger than desired.
This is the first commit of [this work-in-progress branch](https://github.com/Workiva/frugal/compare/develop...brettkail-wk:frugal:dart_smaller).  The final commit there states:
```
The _args/_result structs are only used internally by the generated
client methods, so those structs don't need the full generality of
generated structs, so:
1.  use use_null_for_unset, which produces smaller code
2.  omit methods that not used by the generated client methods
```
The intent of this PR is to merge+release this base class to simplify deployment.
- ~~[ ] Updates to documentation if necessary~~
- ~~[ ] Verify and document changes to any other Messaging components~~
builds on this commit by modifying 
CI only (new/unused API only).
I manually tested …

dart: Add FGeneratedArgsResultBase

---

Dockerfile

The yum update was failing. We don't need this, since it's already called in the base image over at messaging-docker-images successfully so we should already be updated.

MEX-1042 broken builds

---

lib/python/setup.py

I got the following error:
```
ERROR: Cannot install -r requirements.txt (line 3), -r requirements_http.txt (line 4), messaging-sdk and requests==2.31.0 because these package versions have conflicting dependencies.
```
There doesn't seem to be a reason to constrain the upper bound of the `requests` dependency so tightly.

python: Remove dependency upper bound

---

lib/dart/pubspec.yaml

This PR raises the max range in pubspec.yaml(s) to allow resolving to the new major releases w_module 3 and w_transport 5 This is batch 1, batch 2 will raise the minimums.
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/rollout_transport_module_1`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/rollout_transport_module_1)

Rollout w_transport 5, w_module 3

---

lib/dart/pubspec.yaml

This PR raises the minimum in pubspec.yaml(s) to finish resolving to the new major releases w_module 3 and w_transport 5
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/rollout_transport_module_2`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/rollout_transport_module_2)

Rollout w_transport 5, w_module 3 - step 2

---

compiler/generator/dartlang/generator.go
compiler/testdata/expected/dart.int64/variety/f_foo_service.dart
compiler/testdata/expected/dart.nullsafe/variety/f_foo_service.dart
compiler/testdata/expected/dart.nullunset/variety/f_foo_service.dart
compiler/testdata/expected/dart/include_vendor/f_my_service_service.dart
compiler/testdata/expected/dart/variety/f_foo_service.dart

Update frugal compiler code to remove disposable.Disposable to fix analyzer issue:
```
error: The private name '_awaitableFutures', defined by 'disposable.Disposable', conflicts with the same name defined by 'Disposable'.
Try removing 'disposable.Disposable' from the 'with' clause.
```

FEDX-418 : Update generator.go to remove disposable.Disposable
