- .travis.yml
> initial travis

- README.md
> Remove no longer relevant docker section of README

- CONTRIBUTING.md
> Update contributing information

- .travis.yml
> Disable email notifications from travis

- lib/java/.travis.settings.xml
- lib/java/pom.xml
- lib/java/src/main/java/com/workiva/frugal/processor/FProcessor.java
- lib/java/src/main/java/com/workiva/frugal/processor/FProcessorFunction.java
- lib/java/src/main/java/com/workiva/frugal/protocol/HeaderUtils.java
- lib/java/src/main/java/com/workiva/frugal/server/FNatsServer.java
- lib/java/src/main/java/com/workiva/frugal/server/FServer.java
- lib/java/src/main/java/com/workiva/frugal/server/FSimpleServer.java
- lib/java/src/main/java/com/workiva/frugal/transport/FAdapterTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FAsyncTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FNatsTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FSubscriberTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FSubscription.java
- scripts/smithy/smithy_java.sh
@Workiva/messaging-pp also fixed some checkstyle violations
> Java: Update pom to be able to mvn deploy to sonatype

- README.md
@brianshannan-wf @charliestrawn-wf
> Add Homebrew instructions and improve README intro

- skynet.yaml
- smithy.yaml
> Remove out-of-date comments

- skynet.yaml
- smithy.yaml
@Workiva/messaging-pp it was easier to create this myself than to get Rosie's PR reopened.
> Use go1.9 in runner image

- aviary.yaml
@stevenosborne-wf @brianshannan-wf 
@infosec-wf @matthewlorimor-wf
> RED-1848: update aviary.yaml with proper excludes

- compiler/generator/dartlang/generator.go
- test/expected/dart/include_vendor/f_my_scope_scope.dart
- test/expected/dart/variety/f_events_scope.dart
> dart scopes should import Uint8List similar to services

- lib/python/frugal/aio/server/nats_server.py
- lib/python/frugal/aio/transport/nats_scope_transport.py
- lib/python/frugal/aio/transport/nats_transport.py
- lib/python/frugal/tests/aio/server/test_nats_server.py
- lib/python/frugal/tests/aio/transport/test_nats_scope_transport.py
- lib/python/frugal/tests/aio/transport/test_nats_transport.py
This will run message callbacks asynchronously https://github.com/nats-io/asyncio-nats/blob/master/nats/aio/client.py#L788
> Use nats client subscribe async

- lib/java/src/main/java/com/workiva/frugal/server/FDefaultNettyHttpProcessor.java
- lib/java/src/test/java/com/workiva/frugal/server/FDefaultNettyHttpProcessorTest.java
Commits are intended to be reviewed independently.
> Java: Improve Netty

- compiler/generator/golang/generator.go
- compiler/generator/java/generator.go
- compiler/generator/python/asyncio.go
- compiler/generator/python/generator.go
- test/expected/dart/variety/f_foo_service.dart
- test/expected/go/variety/f_foo_service.txt
- test/expected/go/variety_async/f_foo_service.txt
- test/expected/java/boxed_primitives/FFoo.java
- test/expected/java/variety/FFoo.java
- test/expected/java/variety_async/FFoo.java
- test/expected/python.asyncio/variety/f_Foo.py
- test/expected/python.tornado/variety/f_Foo.py
- test/expected/python/variety/f_Foo.py
- test/idl/variety.frugal
> Fix quotes in annotation string literals

- lib/python/requirements_dev_asyncio.txt
- lib/python/setup.py
Upgrade aio nats to get https://github.com/nats-io/asyncio-nats/pull/49
@Workiva/messaging-pp @Workiva/infre-product
> update aio nats

- .travis.yml
- Makefile
- scripts/travis/deploy-java.sh
- scripts/travis/deploy-python.sh
@brianshannan-wf @tylerrinnan-wf
> Fix travis builds for forks, don't publish if not Workiva/frugal, and add a top level makefile.

- lib/java/src/main/java/com/workiva/frugal/transport/FHttpTransport.java
See commit message for a detailed explanation.
> java: Include cause in HTTP TTransportException

- examples/java/pom.xml
- test/integration/java/frugal-integration-test/pom.xml
The following pull request has been created by Doc Services to help us move consumers to the secure artifactory url.
The following changes have been made:
* All instances of `http://artifactory.workiva.org` have been updated to `https://artifactory.workiva.org`.
If you have any questions, please reach out to 
@mairaemperley-wf @macleodbroad-wf
> DS_Artifactory_Updates

- compiler/generator/dartlang/generator.go
- compiler/generator/golang/generator.go
- compiler/generator/java/generator.go
- compiler/generator/python/generator.go
- test/expected/dart/variety/f_foo_service.dart
- test/expected/dart/variety/f_testing_defaults.dart
- test/expected/go/variety/f_foo_service.txt
- test/expected/go/variety/f_types.txt
- test/expected/go/variety_async/f_foo_service.txt
- test/expected/java/boxed_primitives/FFoo.java
- test/expected/java/boxed_primitives/TestingDefaults.java
- test/expected/java/variety/EventWrapper.java
- test/expected/java/variety/TestingDefaults.java
- test/expected/python.asyncio/variety/f_Foo.py
- test/expected/python.asyncio/variety/ttypes.py
- test/expected/python.tornado/variety/f_Foo.py
- test/expected/python.tornado/variety/ttypes.py
- test/expected/python/variety/f_Foo.py
- test/expected/python/variety/ttypes.py
https://jira.atl.workiva.net/browse/INFENG-5814
> INFENG-5814 add struct name to required field error

- Dockerfile
- scripts/smithy/smithy_python.sh
https://jira.atl.workiva.net/browse/INFENG-6094
> INFENG-6094 publish build artifacts

- compiler/generator/golang/generator.go
- test/expected/dart/variety/f_foo_service.dart
- test/expected/go/variety/f_foo_service.txt
- test/expected/go/variety/f_types.txt
- test/expected/go/variety_async/f_foo_service.txt
- test/expected/html/index.html
- test/expected/html/standalone/index.html
- test/expected/html/standalone/variety.html
- test/expected/html/variety.html
- test/expected/java/actual_base/nested_thing.java
- test/expected/java/actual_base/thing.java
- test/expected/java/boxed_primitives/FFoo.java
- test/expected/java/variety/EventsPublisher.java
- test/expected/java/variety/EventsSubscriber.java
- test/expected/java/variety/FFoo.java
- test/expected/java/variety_async/FFoo.java
- test/expected/python.asyncio/variety/f_Foo.py
- test/expected/python.tornado/variety/f_Foo.py
- test/expected/python/variety/f_Foo.py
- test/idl/variety.frugal
Undoes some accidentally breaking name changes in https://github.com/Workiva/frugal/pull/1000 while fixing the original issue.
@Workiva/messaging-pp @Workiva/product2 @ralphmarchildon-wf
> New result args underscores

- lib/java/src/main/java/com/workiva/frugal/server/FServlet.java
- lib/java/src/test/java/com/workiva/frugal/server/FServletTest.java
> java: Write a response for RuntimeException

- compiler/generator/golang/generator.go
- test/expected/go/slim/f_foo_service.go
- test/expected/go/slim/f_types.go
@Workiva/messaging-pp @Workiva/product2 @matthinrichsen-wf
> use correct name to check for new prefix

- Dockerfile
- examples/java/src/main/java/examples/NatsClient.java
- examples/java/src/main/java/examples/NatsPublisher.java
- examples/java/src/main/java/examples/NatsServer.java
- examples/java/src/main/java/examples/NatsSubscriber.java
- lib/java/pom.xml
- lib/java/src/main/java/com/workiva/frugal/server/FNatsServer.java
- lib/java/src/main/java/com/workiva/frugal/transport/FAsyncTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FNatsPublisherTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FNatsSubscriberTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FNatsTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FTransport.java
- lib/java/src/test/java/com/workiva/frugal/benchmarks/NatsBenchmark.java
- lib/java/src/test/java/com/workiva/frugal/server/FNatsServerTest.java
- lib/java/src/test/java/com/workiva/frugal/transport/FNatsPublisherTransportTest.java
- lib/java/src/test/java/com/workiva/frugal/transport/FNatsSubscriberTransportTest.java
- lib/java/src/test/java/com/workiva/frugal/transport/FNatsTransportTest.java
- scripts/skynet/cross/setup_java.sh
- test/integration/java/frugal-integration-test/pom.xml
- test/integration/java/frugal-integration-test/src/main/java/com/workiva/TestClient.java
- test/integration/java/frugal-integration-test/src/main/java/com/workiva/TestServer.java
- Updating jnats to 2.1.1
This should be ready for review now
> Infeng-6076: Upgrade java-nats client in frugal

- examples/java/src/main/java/examples/NatsClient.java
- examples/java/src/main/java/examples/NatsPublisher.java
- examples/java/src/main/java/examples/NatsServer.java
- examples/java/src/main/java/examples/NatsSubscriber.java
- lib/java/pom.xml
- lib/java/src/main/java/com/workiva/frugal/server/FNatsServer.java
- lib/java/src/main/java/com/workiva/frugal/transport/FAsyncTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FNatsPublisherTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FNatsSubscriberTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FNatsTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FTransport.java
- lib/java/src/test/java/com/workiva/frugal/benchmarks/NatsBenchmark.java
- lib/java/src/test/java/com/workiva/frugal/server/FNatsServerTest.java
- lib/java/src/test/java/com/workiva/frugal/transport/FNatsPublisherTransportTest.java
- lib/java/src/test/java/com/workiva/frugal/transport/FNatsSubscriberTransportTest.java
- lib/java/src/test/java/com/workiva/frugal/transport/FNatsTransportTest.java
- scripts/skynet/cross/setup_java.sh
- test/integration/java/frugal-integration-test/pom.xml
- test/integration/java/frugal-integration-test/src/main/java/com/workiva/TestClient.java
- test/integration/java/frugal-integration-test/src/main/java/com/workiva/TestServer.java
Reverts Workiva/frugal#1035
Actually is a breaking change
@Workiva/product2 @Workiva/messaging-pp
> Revert "Infeng-6076: Upgrade java-nats client in frugal"

- Dockerfile
Will cause builds to fail when made against master again
> add back branch env vars in docketfile

- .github/PULL_REQUEST_TEMPLATE.md
Update the PR template to more accurately reflect our requirements for contribution
> Updates PR Template

- Dockerfile
- examples/python.asyncio/stomp_publisher.py
- examples/python.asyncio/stomp_subscriber.py
- lib/python/frugal/aio/transport/__init__.py
- lib/python/frugal/aio/transport/http_transport.py
- lib/python/frugal/aio/transport/nats_scope_transport.py
- lib/python/frugal/aio/transport/stomp_transport.py
- lib/python/frugal/tests/aio/transport/test_stomp_transport.py
- lib/python/frugal/transport/scope_transport.py
- lib/python/requirements_dev_asyncio.txt
- lib/python/setup.py
- scripts/skynet/cross/setup_python.sh
- test/integration/python/aio/client.py
- test/integration/python/aio/publisher.py
- test/integration/python/aio/subscriber.py
- test/integration/python/common/utils.py
- test/integration/tests.json
**Overview**
Similar to how activemq transport is implemented in go and java, the transport uses connections created by [stomp.py](https://github.com/jasonrbriggs/stomp.py) to communicate with the broker.
**Reviewers**
> INFENG-6369: python asyncio activemq frugal transport

- Dockerfile
- scripts/skynet/cross/setup_python.sh
- scripts/smithy/smithy_python.sh
- skynet.yaml
- test/integration/tests.json
Update to messaging-docker-images (built on bionic). 
None
All CI tests should pass
> Update to messaging-docker-images 0.0.29

- scripts/smithy/verify_pr_target.py
Same as https://github.com/Workiva/messaging-sdk/pull/659
> fix pr to master should fail

- compiler/generator/dartlang/generator.go
- test/expected/dart/variety/f_foo_service.dart
- test/expected/dart/variety/f_testing_defaults.dart
@Workiva/product2 @toddbeckman-wf
> fix null check

- compiler/generator/dartlang/generator.go
- examples/dart/gen-dart/v1_music/lib/src/f_album.dart
- examples/dart/gen-dart/v1_music/lib/src/f_purchasing_error.dart
- examples/dart/gen-dart/v1_music/lib/src/f_store_service.dart
- examples/dart/gen-dart/v1_music/lib/src/f_track.dart
- test/expected/dart/actual_base/f_api_exception.dart
- test/expected/dart/actual_base/f_base_foo_service.dart
- test/expected/dart/actual_base/f_nested_thing.dart
- test/expected/dart/actual_base/f_thing.dart
- test/expected/dart/include_vendor/f_my_service_service.dart
- test/expected/dart/include_vendor/f_vendored_references.dart
- test/expected/dart/variety/f_awesome_exception.dart
- test/expected/dart/variety/f_event.dart
- test/expected/dart/variety/f_event_wrapper.dart
- test/expected/dart/variety/f_foo_args.dart
- test/expected/dart/variety/f_foo_service.dart
- test/expected/dart/variety/f_test_base.dart
- test/expected/dart/variety/f_test_lowercase.dart
- test/expected/dart/variety/f_testing_defaults.dart
- test/expected/dart/variety/f_testing_unions.dart
- test/expected/dart/vendor_namespace/f_item.dart
Reverts https://github.com/Workiva/frugal/pull/1040
> Revert https://github.com/Workiva/frugal/pull/1040

- compiler/generator/python/tornado.go
- test/expected/python.tornado/actual_base/f_BaseFoo.py
- test/expected/python.tornado/variety/f_Foo.py
Somehow `self._lock.acquire()` was clearing the current `exc_info`, leading to the actual exception being lost and not raised out of the generated code. Saving the `exc_info` before doing this resolves this problem.
Throwing an exception in a handler locally now gives me:
```
2019-02-27 10:20:43,782 - ERROR - frugal: exception occurred while processing request with correlation id 32097d3f56c646a7bfd0c76fd428830c
Traceback (most recent call last):
File "/Users/brianshannan/dev/wf/msdk-py/lib/python2.7/site-packages/frugal/tornado/processor.py", line 168, in process
yield processor_function.process(context, iprot, oprot)
File "/Users/brianshannan/dev/wf/msdk-py/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
value = future.result()
File …
```
> Tornado correct exceptions

- examples/java/src/main/java/examples/NatsClient.java
- examples/java/src/main/java/examples/NatsPublisher.java
- examples/java/src/main/java/examples/NatsServer.java
- examples/java/src/main/java/examples/NatsSubscriber.java
- lib/java/pom.xml
- lib/java/src/main/java/com/workiva/frugal/server/FNatsServer.java
- lib/java/src/main/java/com/workiva/frugal/transport/FAsyncTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FNatsPublisherTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FNatsSubscriberTransport.java
- lib/java/src/main/java/com/workiva/frugal/transport/FNatsTransport.java
- lib/java/src/test/java/com/workiva/frugal/benchmarks/NatsBenchmark.java
- lib/java/src/test/java/com/workiva/frugal/server/FNatsServerTest.java
- lib/java/src/test/java/com/workiva/frugal/transport/FNatsPublisherTransportTest.java
- lib/java/src/test/java/com/workiva/frugal/transport/FNatsSubscriberTransportTest.java
- lib/java/src/test/java/com/workiva/frugal/transport/FNatsTransportTest.java
- scripts/skynet/cross/setup_java.sh
- test/integration/java/frugal-integration-test/pom.xml
- test/integration/java/frugal-integration-test/src/main/java/com/workiva/TestClient.java
- test/integration/java/frugal-integration-test/src/main/java/com/workiva/TestPublisher.java
- test/integration/java/frugal-integration-test/src/main/java/com/workiva/TestServer.java
Updates jnats to latest 2.4.1, basically reopens https://github.com/Workiva/frugal/pull/1035.
> Infeng-7520: Update jnats to latest version 2.4.1 in frugal

- compiler/generator/java/generator.go
- examples/java/src/main/java/v1/music/FStore.java
- test/expected/java/actual_base/FBaseFoo.java
- test/expected/java/boxed_primitives/FFoo.java
- test/expected/java/deprecated_logging/FFoo.java
- test/expected/java/valid_vendor/FMyService.java
- test/expected/java/valid_vendor_no_path/FMyService.java
- test/expected/java/variety/FFoo.java
- test/expected/java/variety_async/FFoo.java
- test/expected/java/vendored_but_no_use_vendor/FMyService.java
N/A
Manually verified logging in a service that attempts to send a response that is too large.
See commit message.
@Workiva/product2 @brandonbodnar-wk
> java: Improve logging of response buffer overflow

- examples/java/pom.xml
- test/integration/java/frugal-integration-test/pom.xml
Move all references to artifactory pro
legacy artifactory is dead, long live artifactory pro
Integration tests pass. Example works properly.
👍 
> Java: Point to artifactory pro

- lib/java/pom.xml
- test/integration/java/frugal-integration-test/pom.xml
Bump jnats version to 2.4.2 to pickup some bugfixes
> jnats 2.4.2

- compiler/generator/dartlang/generator.go
- test/expected/dart/actual_base/f_actual_base_dart_constants.dart
- test/expected/dart/variety/f_testing_defaults.dart
- test/expected/dart/variety/f_variety_constants.dart
- test/expected/dart/vendor_namespace/f_vendor_namespace_constants.dart
[INFENG-7871](https://jira.atl.workiva.net/browse/INFENG-7871)
In theory, it should be possible to resolve indirect constants, but there is currently no infrastructure for resolving indirect constants linearly (and without infinite loops), so the PR skips those scenarios for now.
> dart: Use const for simple constants

- compiler/generator/dartlang/generator.go
- test/expected/dart/variety/f_variety_constants.dart
- test/expected/go/slim/f_types.go
- test/expected/go/variety/f_types.txt
- test/expected/gopherjs/variety/f_types.go
- test/expected/html/index.html
- test/expected/html/standalone/index.html
- test/expected/html/standalone/variety.html
- test/expected/html/variety.html
- test/expected/java/variety/varietyConstants.java
- test/expected/python.asyncio/variety/constants.py
- test/expected/python.tornado/variety/constants.py
- test/expected/python/variety/constants.py
- test/idl/variety.frugal
> dart: Fix constant set type parameter

- Dockerfile
- skynet.yaml
> INFENG-8001 Fix build

- lib/go/protocol.go
@Workiva/product2 @kevinsimons-wf
> initialize ephemeral properties when reading an FContext

- compiler/generator/dartlang/generator.go
- test/expected/dart/actual_base/f_actual_base_dart_constants.dart
- test/expected/dart/variety/f_variety_constants.dart
- test/expected/dart/vendor_namespace/f_vendor_namespace_constants.dart
@Workiva/product2 @evanweible-wf
> dart:convert.dart -> dart:convert

- .gitignore
- Dockerfile
- scripts/skynet/cross/setup_python.sh
- skynet.yaml
New version of messaging-docker-images just dropped (based on AL2) - upgrade to it.
None.
Tests pass.
Tests pass!
> Update to the newest messaging-docker-images version

- compiler/compiler.go
Commit is best reviewed with whitespace ignored.
> Simplify recurse processing

- lib/python/frugal/aio/transport/http_transport.py
See https://github.com/aio-libs/aiohttp/issues/2865
Fixed here: https://github.com/aio-libs/aiohttp/pull/2972
`ClientSession` from aiohttp accepts a timeout in seconds, if not set, will default to 5 minutes. We should pass timeout from FContext to `ClientSession` too. 
> INFENG-11229: Pass timeout to aiohttp ClientSession

- compiler/generator/dartlang/generator.go
- examples/dart/gen-dart/v1_music/lib/src/f_store_service.dart
- examples/dart/gen-dart/v1_music/pubspec.yaml
- lib/dart/lib/src/frugal/f_provider.dart
- test/expected/dart/actual_base/f_base_foo_service.dart
- test/expected/dart/include_vendor/f_my_service_service.dart
- test/expected/dart/include_vendor/pubspec.yaml
- test/expected/dart/variety/f_foo_service.dart
- test/expected/dart/vendor_namespace/f_vendored_base_service.dart
> CPLAT-10441: Revert "CPLAT-10353: Manage frugal service objects"

- scripts/update.py
I introduced a syntax error into the update script. We don't want syntax errors.
TODO
TODO
TODO
> Fix update script syntax error

- scripts/lang/dart.py
- scripts/update.py
- test/common_test.go
- test/integration/main.go
- With Go 1.13+, flag.Parse is handled differently and the way the testing is written here needs to be updated to work.
- Also a few changes to the release scripts (to reflect similar changes to messaging-sdk release scripts).
N/A
- Using Go 1.13+, run `python ./scripts/update.py --version v3.9.5`
- Update process succeeded with expected results.
> SAPI-1500: Update testing

- lib/dart/pubspec.yaml
`mockito` is not needed as a normal dep and should be downgraded to a dev dep.
TODO
CI Passing should be sufficient.
TODO
@evanweible-wf @maxwellpeterson-wf 
> INFENG-11460: Move mockito to dev dependency

- scripts/update.py
update.py script creating bad new files due to path.
N/A
- On current develop branch, run `python scripts/update.py --version v3.9.5`, there will be a test/'../ directory.
- On this branch, run the same and get no weird directory.
Ran locally myself, same as expected in steps above.
@yuanmwang-wf
> INFENG-11590: Fix output path

- .travis.yml
- Makefile
- lib/go/go.mod
- lib/java/pom.xml
- scripts/skynet/cross/setup_java.sh
- scripts/skynet/cross/setup_python.sh
- scripts/skynet/run_cross_skynet.sh
- test/integration/readme.md
Setting up test framework for working on https://jira.atl.workiva.net/browse/SPLAT-108
I tried to capture all the things I had to do in the `## Assumptions` section of the integration tests `readme.md`
`wk test run cross-local`
I was using the wk tool to wrap the skynet CLI, either should work.
All tests passed
> Got cross and cross-local tests working on my box

- compiler/generator/dartlang/generator.go
- examples/dart/gen-dart/v1_music/pubspec.yaml
- examples/dart/pubspec.yaml
- examples/dart/web/index.html
- lib/dart/pubspec.yaml
- test/expected/dart.nullunset/include_vendor/pubspec.yaml
- test/expected/dart/include_vendor/pubspec.yaml
- test/integration/dart/gen-dart/frugal_test/pubspec.yaml
Bump minimum thrift version
You can run the example app
> SPLAT-187 Consume new thrift dart

- lib/python/frugal/protocol/protocol.py
- lib/python/frugal/server/http_server.py
- lib/python/requirements.txt
- lib/python/setup.py
Need to consume thrift 0.13.0 and adjust the python lib to accommodate changes to thrift python code.
N/A
Example service/client now work with thrift 0.13.0 as well as all unit/integration tests.
Client:
```
(frugal)charliekump: ~/go/src/github.com/Workiva/frugal/examples/python (python_thrift_0.13.0)
$ python http_client.py
2020-09-17 14:29:06,053 - INFO - Starting...
2020-09-17 14:29:06,060 - DEBUG - Starting new HTTP connection (1): localhost:9090
2020-09-17 14:29:06,063 - DEBUG - http://localhost:9090 "POST /frugal HTTP/1.1" 200 352
2020-09-17 14:29:06,063 - INFO - Bought an album Album(tracks=[Track(title='Comme des enfants', artist='Coeur de pirate', publisher='Grosse Boîte', composer='Béatrice Martin', duration=169.0, pro=1)], duration=12000.0, …
```
> SPLAT-81: Python thrift 0.13.0

- lib/python/frugal/tests/aio/server/test_http_handler.py
- lib/python/setup.py
Pinned dep was causing dependency issues, use range instead.
> SPLAT-575 Update nats-asyncio dep to latest

- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yaml
> Remove yuanmwang-wf from dependabot config

- .github/dependabot.yaml
With the repo's new gomod structure, lets update dependabot too
* Remove Erik from reviewers list (no longer on the service platform team)
* Add `/`, `/test/integration` and `/examples/go` to updated directories.
TODO
TODO
TODO
> Update Dependabot Config

- compiler/compiler.go
I'd like to use these functions in a standalone app external to frugal (to basically build https://github.com/Workiva/frugal/pull/1651 in a different location).
Let's export them!
none
CI passing? just smoke test that I didn't accidentally break anything
CI passing/still building should be sufficient
> Export a few functions from the `compile` package

- README.md
> remove glide from readme

- lib/python/frugal/tests/aio/server/test_http_handler.py
- lib/python/requirements_dev_asyncio.txt
- lib/python/setup.py
Teams wanting newer versions of aiohttp.
N/A
Tests updated
Test Pass
> Upgrade aiohttp range

- Dockerfile
- skynet.yaml
> MEX-965: Latest image

- .github/dependabot.yaml
Failing to download from private registry:
> Add artifactory auth

- compiler/parser/parser.go
Tested against Workiva-internal audit-api.frugal:
wk/develop:
```
$ time frugal --out x -gen json audit-api.frugal
real	0m19.640s
user	0m36.213s
sys	0m0.603s
```
branch:
```
$ time frugal --out x -gen json audit-api.frugal
real	0m0.709s
user	0m0.401s
sys	0m0.056s
```
Additionally, the output is equivalent for all output formats (JSON, Go, Dart, Java).
@travissmith-wf
> Cache parsed include files

- lib/python/setup.py
> Expand aiohttp version range

- lib/java/src/main/java/com/workiva/frugal/server/FJakartaServlet.java
- lib/java/src/main/java/com/workiva/frugal/server/FServlet.java
- lib/java/src/test/java/com/workiva/frugal/server/FJakartaServletTest.java
- lib/java/src/test/java/com/workiva/frugal/server/FServletTest.java
See commit message for stack trace details.
N/A
Ran the test suite of a service using `FJakartaServlet`.
N/A
fyi: @charliestrawn-wf @jimsimon-wk
> java: Avoid suppressed exceptions after a servlet write exception

- lib/dart/pubspec.yaml
> Add logging back to pubspec
